name: publish-snapshot
on:
  push:
    branches: ["main"]

jobs:
  publish:
    if: ${{ !contains(github.event.head_commit.message, '[CI-SKIP]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Perform Tests
        run: gradle check

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: AE8D48AD105A7BD6891C33B905E5302EC4C69955
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Publish
        uses: uTen2c/publish-to-github@v1
        with:
          repo: turtton/maven-repo
          token-user: turtton
          token: ${{ secrets.TOKEN }}
          commit-user-name: turtton
          commit-user-email: "top.gear7509@turtton.net"
